### ISSUE TITLE
Move opinionated operators elsewhere

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/jitdb#11]
We should keep JITDB unopinionated, JITDB should only assume: 

- There is an `async-flumelog` using `flumecodec/json`
- JSON Messages stored in the log are of the following format

```
{
  key: MsgId,
  value: {
    previous: MsgId,
    author: FeedId,
    sequence: number,
    timestamp: number,
    hash: 'sha256',
    content: any, 
    signature: string,
  };
  timestamp: number,
}
```

I.e. JITDB doesn't assume what `msg.value.content` internally looks like. Currently in JITDB we have some things that assume SSB message conventions, and these should be moved to a more opinionated module:

- [ ] `jitdb/operators/type`
- [ ] `jitdb/operators/channel`
- [ ] `jitdb/operators/isRoot`
- [ ] `jitdb/operators/isPrivate`

**Comment by staltz** [comment]
I think I figured out what to do about this issue! Turns out that operators like `type`, `author`, `channel` are not the building blocks. JITDB should have operators for the *operations* that JITDB supports: DATA, EQUAL, AND, OR, GT, GTE, LT, LTE.

Currently we have some but are missing some others:

- [x] `and` for AND
- [x] `or` for AND
- [ ] `equal` for EQUAL
- [ ] `gt` for GT
- [ ] `gte` for GTE
- [ ] `lt` for LT
- [ ] `lte` for LTE
- [ ] `data` for `DATA` (I'd love to rename this to `POSITION` actually, I find the word "DATA" not descriptive and already overused for other parts inside JITDB)

`equal` wouldn't be so ergonomic to use, because it requires an `indexType` and a `seek` function (which should be written by hand intelligently to optimize for performance). That said, we could have two operators for EQUAL:

- `equal(helpers.seekType, 'post', 'type')`
- `slowEqual('value.content.type', 'post')`

`slowEqual` make it easy to quickly experiment with queries, it builds the seek function by doing a `.split('.')` on the first argument. The explicit name "slow" encourages developers to not use this if they care about performance.

In practice, opinionated operators like `type`, `author`, `channel`, `isRoot`, `isPrivate` would live in ssb-db2/social and would **wrap** `equal` so to guarantee good performance.

**Comment by arj03** [comment]
> I think I figured out what to do about this issue! Turns out that operators like `type`, `author`, `channel` are not the building blocks. JITDB should have **operators for the _operations_** that JITDB supports: DATA, EQUAL, AND, OR, GT, GTE, LT, LTE.

True, they get quite a bit more verbose.

>     * [ ]  `data` for `DATA` (I'd love to rename this to `POSITION` actually, I find the word "DATA" not descriptive and already overused for other parts inside JITDB)

:+1: 

> `slowEqual` make it easy to quickly experiment with queries, it builds the seek function by doing a `.split('.')` on the first argument. The explicit name "slow" encourages developers to not use this if they care about performance.

:+1: 

> In practice, opinionated operators like `type`, `author`, `channel`, `isRoot`, `isPrivate` would live in ssb-db2/social and would **wrap** `equal` so to guarantee good performance.

Maybe its own module, but yes. Would make sense for the README to mention this even if the operators is outside the main module as its really nice syntactic sugar.

**Comment by staltz** [comment]
Yeah I'm sure we'll find a good module where "all" the operators should go.

I think JITDB will be hidden from normal developer's perspective (much like flumelog is mostly hidden from a developer using ssb-db), so people won't resort too often to this repo for the operator docs.

**Comment by arj03** [comment]
We should probably add offsets and sequences instead of DATA or POSITION directly. Working on offsets to try that out in ssb-db2.

**Comment by staltz** [comment]
Yes, fully agreed with OFFSETS and SEQUENCES. The implicit "or" was funny, initially it seemed to me that we have to pass both offsets and sequences fields.

**Comment by staltz** [comment]
done by #27
