### ISSUE TITLE
deferred() to support cancellation

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/jitdb#163]
## Problem

(Read a verbose context below, here is just the summary:) if there is a long-running async job running in a `deferred()` operator, there is no way of cancelling that job even if we have given up on the query. This is because deferred is based on simple callbacks and promises.

## Solution A

One way to fix this, which is a breaking change (anyway using `deferred` would have to update their code): change `deferred()` to be based on pull-streams, or any other async primitive that supports cancellations (I believe: pull-stream, push-stream, Callbags, RxJS, etc). This affects both the internals of `executeDeferredOps` as well as how the `deferred`s are used in practice by app developers.

## Solution B

Another way, less disruptive, but more ad-hoc: change the arguments of `deferred()`, from `deferred((meta, cb) =>` to `deferred((meta, cb, onAbort) =>`. This would avoid a breaking change, and `onAbort` is used like this:

```js
  deferred((meta, cb, onAbort) => {
    let timer = setTimeout(() => {
      timer = null
      cb(null, slowEqual('value.author', alice.id))
    }, 30e3)
    
    onAbort(() => {
      if (timer) {
        clearTimeout(timer)
        timer = null
      }
    })
  })
```

## Context

In a full-text search plugin (custom ssb-db2 index), suppose the user is going to type `little red riding hood`, but they first type `little`, then `red`, then `riding`, then `hood`, and suppose the app developer is triggering a search query every time a word is completed (as opposed to only triggering it once upon pressing keyboard Enter).

We will trigger 4 different searches: 

- `little` 
- `little red`
- `little red riding`
- `little red riding hood`

How can we cancel the previous searches? Once `little red` starts running, we should cancel the indexing reading task for the obsolete `little` search. Doing this with pull-streams is rather easy, because if there was a source pull-stream for `little`, we just abort that stream and start pulling the next one.

But I'd like to provide my plugin as an ssb-db2 operator, similar to fullMentions, so you can compose the search results with other ssb-db2 operations. The basic use case for this will be just to search for *public* `little red riding hood` messages of type `post`.

But the way that fullMentions does it is through `deferred` and a single callback, inside that `deferred` we are doing a `pull-level` read of the index, and `pull.collect` of all the results and then returning that to the callback. And this way of doing stuff doesn't allow cancellation.

**Comment by staltz** [comment]
@arj03 I think I like solution B, what are your thoughts on that?

**Comment by arj03** [comment]
Agree, I like option B. If you don't do anything on the `onAbout` it works like it did before.
