### ISSUE TITLE
`paginate` memory use

### ISSUE THREAD

**Issue by nichoth** [ssb-ngi-pointer/jitdb#188]
How does the pagination operator work? I ask because it's using a lot of memory/time every time I call it, like it has do traverse the entire DB or something.

This is the test case I'm using -- https://github.com/planetary-social/viewer/blob/9279c7ab745bf34ac684969c13af441ff1a26157/index.js#L192

It's hard to reproduce this in a controlled way, because you need a DB with a lot of data in it, so for example a 'real' pub, that has real data in it. 

The example file I linked above is actually 1 level deep in my dependency graph. It is used by a test pub I have set up -- https://github.com/planetary-social/planetary-pub

You can see this pub live on the internet by going to https://pub2.onrender.com/feed/alice . However the site will crash when you visit it because of the memory usage.

Another way to reproduce the failing test is to run it locally. So clone the pub repo, then type
```
NODE_ENV=staging npm start
```
and then visit `http://localhost:8888/feed/cel` . You will see that it does not crash like the hosted server because you have more ram on your machine, but it does take a long time to finish.

So the question — am I doing something wrong in my query, or is this an issue with the DB?

thanks. that was a lot of description

**Comment by arj03** [comment]
You should use `toPullStream` together with paginate. See https://github.com/ssb-ngi-pointer/jitdb#pagination

**Comment by nichoth** [comment]
Ah ok. I was under the impression that the paginate operator would create a stream of 'pages' of results, so a stream like 

```
stream([post, post,...], [post, post,...])
```

and `toCallback` would return just the first 'page' from above, not have to do more work than the pull stream version.

**Comment by nichoth** [comment]
So to put things more concretely, this is how I would use `paginate`?

```js
            var source = sbot.db.query(
                where(
                    and(
                        // slowEqual('value.content.type', 'contact'),
                        type('post'),
                        author(id)
                    )
                ),
                paginate(10),
                descending(),
                toPullStream()
            )
```

And you would then do this to get the first page?
```js
            S(
                source,
                S.take(1),
                S.drain(msgs => {
                })
            )
```

It seems like it is just as resource intensive as the last version. I'm worried that I'm doing something wrong

**Comment by nichoth** [comment]
https://github.com/planetary-social/viewer/blob/main/index.js#L131

**Comment by nichoth** [comment]
I would be ok with doing a call/synchronous chat also if you think that would be fastest for figuring this out

**Comment by arj03** [comment]
> would then do this to get the first page

Yes. I have tested this locally using:

```
const source = ssb.db.query(
  where(
    and(
      type('post'),
      author('@6CAxOI3f+LUOVrbAl0IemqiS7ATpQvr9Mdw9LC4+Uv0=.ed25519')
    )
  ),
  paginate(10),
  descending(),
  toPullStream()
)

console.time("query")

pull(
  source,
  pull.take(1),
  pull.drain(msgs => {
    console.timeEnd("query")
    console.log(msgs.length)
  })
)
```

this returns in 400ms

> It seems like it is just as resource intensive as the last version. I'm worried that I'm doing something wrong

What do you mean with resource intensive? Memory / cpu time?

**Comment by nichoth** [comment]
The end goal is to make a web-viewer app using ssb-db2, so we need to paginate since it's using http request/response. 

I think it's using too much memory which then crashes the server (the 502 seen here)

![image](https://user-images.githubusercontent.com/5776508/148284282-d1429587-ca2f-4fcb-bda9-ac84fc898c9f.png)

I can try to put together a reproducible test case. I suppose I would want to add a lot of data to a local DB, then run the query

**Comment by arj03** [comment]
It must be something other than the paginate query. I ran it locally on a 1GB database and the memory usage was 1,8%.

**Comment by nichoth** [comment]
hmm ok thank you for helping

**Comment by nichoth** [comment]
My coworker had mentioned something about indexes earlier, which makes me wonder if I should be doing something to index data before running the query

```js
            var source = sbot.db.query(
                where(
                    and(
                        type('post'),
                        author(id)
                    )
                ),
                descending(),
                paginate(10),
                toPullStream()
            )
```

**Comment by arj03** [comment]
The first time you run a new query, indexes will be created. Afterwards things will be fast. Note author is not dedicated so works on [any author](https://github.com/ssb-ngi-pointer/ssb-db2/blob/7f23695f8bd59fc8f3ee3f476e1b0f5da69ec6f9/operators/index.js#L57)

**Comment by nichoth** [comment]
The only other part of that route is a call to `sbot.suggest.profile`. Do you know if that could be causing the memory use?

https://github.com/planetary-social/viewer/blob/e0b95c109b5702de4e85c4a6ab9113757ad63ed2/index.js#L48

**Comment by nichoth** [comment]
It looks like it was my use of the `threads` plugin that was making it slow. thanks for your help
