### ISSUE TITLE
Seekers should not return undefined

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/jitdb#210]
We typically return undefined if the field pointer was -1:

https://github.com/ssb-ngi-pointer/jitdb/blob/1dc806047567b1321fe52494f76b8cb01d846c4a/test/helpers.js#L41

This could be a problem if we later check the return value of these seeker functions, like here:

https://github.com/ssb-ngi-pointer/jitdb/blob/1dc806047567b1321fe52494f76b8cb01d846c4a/index.js#L315-L317

Shouldn't we always return `-1` instead of `undefined`? Could this have been a source of bugs?

Note:

```
> ~-1
0

> !~-1
true

> ~0
-1

> !~0
false

> ~undefined
-1

> !~undefined
false
```

cc @arj03

**Comment by arj03** [comment]
Yep, that looks incorrect
