### ISSUE TITLE
get just one result

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/jitdb#215]
ssb-db2 `getMsg` API could be optimized. Instead of using jitdb `all()`, we can just do:

- `msgId` input
- `keys` leveldb index gives us the `seq`
- We pass the `seq` to a new API in jitdb that gives the `offset`
- We look up the record from the log using `offset`

I bet this is going to be great for performance because maybe setting up bitvectors and scanning them and all of that stuff might be non-negligible once you have lots of `getMsg` going on.

**Comment by staltz** [comment]
@arj03 Actually I realized that I wanted to ask what you think about **this** issue, not the other one. :sweat_smile:

**Comment by arj03** [comment]
:D I was also a bit surprised by the other one. Anyway, I think this optimization could make sense, I'm just not sure how often `getMsg` is called.

**Comment by staltz** [comment]
getMsg would be called for every delete, which I think when there's many deletes it would become a big deal. And then in ssb-threads, getMsg is used often to get the root msg of a thread, and it processes many threads.
