### ISSUE TITLE
More docs on equal 

### ISSUE THREAD

**Issue by mixmix** [ssb-ngi-pointer/jitdb#22]
The docs on `slowEqual` and `equal` are clear but currently provide happy paths which seem to use convenience helpers provided by db - seekType, seekAuthor

I would love to know how to write a seek for a profile tangle matching an Id.

The docs talk about manipulating a buffer. I should probably dig in to find where seekAuthor is defined.

My wishlist would behave like

```
seekTangle(tangleName, id)

// inside it would do
msg.key === id ||
msg.value.content.tangles[tangleName].root === id
```

If anyone would like to pair on this I'd love to. 

This issue and this request are not at all urgent, please feel free to address way later

**Comment by staltz** [comment]
Hopefully this is done now? More docs on how to do the tangles thing you mentioned could be written later, or maybe in ssb-db2

**Comment by mixmix** [comment]
Yeah loved what you showed. I can figure out the tangle thing myself from
what I've learnt i reckon!
