### ISSUE TITLE
operator `liveOnly()`

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/jitdb#75]
Very similar to `live()`, but sets `meta.liveOnly = true`, and in toPullStream() we check meta.live and meta.liveOnly, and do the pull-cat accordingly.

Use case: when we don't want old values in the live stream.

@arj03 Could you do this one? (PS: as I'm putting ssb-db2 in manyverse i'm mapping out what's still needed)

**Comment by staltz** [comment]
Arguably there might be different ways of doing this, e.g. `live({ old: false })` is also one API

**Comment by arj03** [comment]
Sure

**Comment by arj03** [comment]
I opted for the: live() is old=false by default, and one would have to do live({ old: true }) to opt-in.

I think that is what most people would expect to happen.
